Update drupal and purger docs with more information.
quantcdn/docs pull request #81
Opened 2023-11-03 06:32 UTC by kepol

Docs were missing information about using:

```
$settings['queue_service_quant_seed_worker'] = 'quant.queue_factory';
```

from https://github.com/quantcdn/drupal/pull/149

I also added new images and did some cleanup.

2023-11-06 01:05 UTC, steveworley requested changes
Looks good! Just a minor update to the queue unique reasoning.

2023-11-06 01:05 UTC, steveworley commented on docs/integrations/drupal/purger.md
> +When using `drush` without this setting, duplicates may be processed which can slow down seeding significantly.
```suggestion
This changes the database driver that is used when managing the purge queue. Drupal's database queue driver creates a unique item each which leads to duplicate items being added to the queue which will negatively impact the seed time for your website. The driver provided by Quant is optimised for Quant's used case.
```

Just a quick update — this setting changes the [database queue factory](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Queue%21DatabaseQueue.php/10.0.x) to a custom one provided by Quant. This essentially updates the way that queue items are inserted into the table, a unique ID is added per item which cannot be duplicated. The insert method will catch the error and skip creating duplicate rows.

2023-11-06 01:36 UTC, kepol commented
Sounds good, thanks!

2023-11-27 04:52 UTC, steveworley approved these changes

2023-11-27 04:55 UTC, merged